Patched LuaLaTeX configuration. Installed nodejs. Installed mermaid in nodejs. Use package files. Added sanity checks.

diff --git a/.github/workflows/Pipeline.yml b/.github/workflows/Pipeline.yml
--- a/.github/workflows/Pipeline.yml
+++ b/.github/workflows/Pipeline.yml
@@ -1,13 +1,13 @@
-name: Build MikTeX images
+name: Build MiKTeX images
 
 on:
   push:
   workflow_dispatch:
 
 jobs:
-  MikTeX:
-    name: 🛳️ Build MikTeX base-image
-    runs-on: ubuntu-24.04
+  MiKTeX:
+    name: 🛳️ Build MiKTeX base-image
+    runs-on: 'ubuntu-24.04'
 
     outputs:
       base_image_os_version:    ${{ steps.variables.outputs.base_image_os_version }}
@@ -25,7 +25,7 @@ jobs:
         id: variables
         run: |
           base_image_name="python"
-          base_image_os_version="13"
+          base_image_os_version="12"
           base_image_os_codename="Bookworm"
           base_image_os_size="-slim"
           base_image_py_version="3.14"
@@ -53,7 +53,7 @@ jobs:
       - name: ⏬ Checkout repository
         uses: actions/checkout@v6
 
-      - name: 🐋 Building MikTeX image
+      - name: 🐋 Building MiKTeX image
         id: build
         run: |
           ANSI_RED=$'\x1b[31m'
@@ -78,6 +78,10 @@ jobs:
             docker image inspect $1 --format='{{.Size}}' | numfmt --to=iec --format '%.2f'
           }
 
+          printf -- "Convert 'Base.packages' to 'Debian.packages' ...\n"
+          RemoveComments Base.packages Debian.packages
+          printf -- "Convert 'Common.packages' to 'Install.packages' ...\n"
+          RemoveComments Common.packages Install.packages
           printf -- "Convert 'Common.list' to 'Packages.list' ...\n"
           RemoveComments Common.list Packages.list
 
@@ -86,8 +90,8 @@ jobs:
             --file Dockerfile \
             --build-arg IMAGE=${{ steps.variables.outputs.base_image }} \
             --build-arg MIKTEX_SRC_REPO=${{ steps.variables.outputs.miktex_source_repository }} \
-            --label "org.opencontainers.image.title=MikTeX on Debian ${{ steps.variables.outputs.base_image_os_version }} (${{ steps.variables.outputs.base_image_os_codename }}) + Python ${{ steps.variables.outputs.base_image_py_version }}" \
-            --label "org.opencontainers.image.description=MikTeX on Debian ${{ steps.variables.outputs.base_image_os_version }} (${{ steps.variables.outputs.base_image_os_codename }}) + Python ${{ steps.variables.outputs.base_image_py_version }} image maintained by pyTooling Authors." \
+            --label "org.opencontainers.image.title=MiKTeX on Debian ${{ steps.variables.outputs.base_image_os_version }} (${{ steps.variables.outputs.base_image_os_codename }}) + Python ${{ steps.variables.outputs.base_image_py_version }}" \
+            --label "org.opencontainers.image.description=MiKTeX on Debian ${{ steps.variables.outputs.base_image_os_version }} (${{ steps.variables.outputs.base_image_os_codename }}) + Python ${{ steps.variables.outputs.base_image_py_version }} image maintained by pyTooling Authors." \
             --label "org.opencontainers.image.authors=Patrick Lehmann <Paebbels@gmail.com>" \
             --label "org.opencontainers.image.vendor=pyTooling" \
             --label "org.opencontainers.image.version=1.0" \
@@ -104,7 +108,7 @@ jobs:
             --label "pyTooling.dockerimages.os.packagemanager=apt" \
             --label "pyTooling.dockerimages.os.fullname=Debian ${{ steps.variables.outputs.base_image_os_version }} (${{ steps.variables.outputs.base_image_os_codename }})" \
             --label "pyTooling.dockerimages.py.version=${{ steps.variables.outputs.base_image_py_version }}" \
-            --label "pyTooling.dockerimages.application.name=MikTeX" \
+            --label "pyTooling.dockerimages.application.name=MiKTeX" \
             --tag "${{ steps.variables.outputs.miktex_image }}" \
             . 2>&1 \
           | ./Docker.buildx.sh
@@ -112,7 +116,7 @@ jobs:
           
           printf -- "Docker image '%s' has %s\n" "${{ steps.variables.outputs.miktex_image }}" "$(DockerImageSizeUncompressed ${{ steps.variables.outputs.miktex_image }})"
 
-      - name: ☑ Checking MikTeX image '${{ steps.variables.outputs.miktex_image }}'
+      - name: ☑ Checking MiKTeX image '${{ steps.variables.outputs.miktex_image }}'
         id: test
         run: |
           DockerImageSizeUncompressed() {
@@ -126,7 +130,7 @@ jobs:
           docker container run --rm ${{ steps.variables.outputs.miktex_image }} bash -c 'printf "%s\n" "which pdflatex: $(which pdflatex) ($(pdflatex --version | head -n 1))"'
           MIKTEX_VERSION="$(docker container run --rm ${{ steps.variables.outputs.miktex_image }} bash -c "miktex --version | head -n 1")"
           
-          printf -- "MikTeX version (raw): %s\n" "${MIKTEX_VERSION}"
+          printf -- "MiKTeX version (raw): %s\n" "${MIKTEX_VERSION}"
           MIKTEX_VERSION="$(echo "${MIKTEX_VERSION}" | grep -oP '\(MiKTeX \d+\.\d+\)' | grep -oP '\d+\.\d+')"
           
           tee "${GITHUB_OUTPUT}" <<EOF
@@ -145,11 +149,32 @@ jobs:
           printf -- "Docker image '%s' has %s\n" "${{ steps.variables.outputs.miktex_image }}" "$(DockerImageSizeUncompressed ${{ steps.variables.outputs.miktex_image }})"
           docker image push ${{ steps.variables.outputs.miktex_image }}
 
-  Specific:
-    name: ${{ matrix.icon }} Build specific MikTeX image for ${{ matrix.name }}
-    runs-on: ubuntu-24.04
+  SanityCheck:
+    name: Check MiKTeX installation
+    runs-on: 'ubuntu-24.04'
     needs:
-      - MikTeX
+      - MiKTeX
+    container:
+      image: ${{ needs.MiKTeX.outputs.miktex_image }}
+      volumes:
+        - ${{ github.workspace }}/latex:/latex
+    steps:
+      - name: Check default shell
+        run: |
+          printf -- "Checking active shell ...\n"
+          activeShell=$(readlink /proc/$$/exe)
+          if [ "$activeShell" == "$(which bash)" ]; then
+            printf -- "  Shell is Bash (%s - version %s) \x1b[92m[OK]\x1b[0m\n" "$activeShell" "$(/bin/bash --version | head -n 1)"
+          else
+            printf -- "  Shell is %s \x1b[91m[FAILED]\x1b[0m\n" "$activeShell"
+            exit 1
+          fi
+
+  Specific:
+    name: ${{ matrix.icon }} Build specific MiKTeX image for ${{ matrix.name }}
+    runs-on: 'ubuntu-24.04'
+    needs:
+      - MiKTeX
     strategy:
       fail-fast: false
       matrix:
@@ -161,16 +186,16 @@ jobs:
         id: variables
         run: |
           tee "${GITHUB_OUTPUT}" <<EOF
-          specific_image_ns="${{ needs.MikTeX.outputs.miktex_image_ns }}"
-          specific_image_name="${{ needs.MikTeX.outputs.miktex_image_name }}"
+          specific_image_ns="${{ needs.MiKTeX.outputs.miktex_image_ns }}"
+          specific_image_name="${{ needs.MiKTeX.outputs.miktex_image_name }}"
           specific_image_tag="${{ matrix.name }}"
-          specific_image=${{ needs.MikTeX.outputs.miktex_image_ns }}/${{ needs.MikTeX.outputs.miktex_image_name }}:${{ matrix.image }}
+          specific_image=${{ needs.MiKTeX.outputs.miktex_image_ns }}/${{ needs.MiKTeX.outputs.miktex_image_name }}:${{ matrix.image }}
           EOF
 
       - name: ⏬ Checkout repository
         uses: actions/checkout@v6
 
-      - name: 🐋 Building MikTeX image for ${{ matrix.name }}
+      - name: 🐋 Building MiKTeX image for ${{ matrix.name }}
         id: build
         run: |
           ANSI_RED=$'\x1b[31m'
@@ -195,15 +220,19 @@ jobs:
             docker image inspect $1 --format='{{.Size}}' | numfmt --to=iec --format '%.2f'
           }
 
+          printf -- "Convert '${{ matrix.name }}.packages' to 'Install.packages' ...\n"
+          RemoveComments ${{ matrix.name }}.packages Install.packages
+          printf -- "Convert '${{ matrix.name }}.npm' to 'Install.npm' ...\n"
+          RemoveComments ${{ matrix.name }}.npm Install.npm
           printf -- "Convert '${{ matrix.name }}.list' to 'Packages.list' ...\n"
           RemoveComments ${{ matrix.name }}.list Packages.list
 
           printf -- "Building docker file 'Dockerfile' ...\n"
           docker buildx build \
             --file Dockerfile.Specific \
-            --build-arg "IMAGE=${{ needs.MikTeX.outputs.miktex_image }}" \
-            --label "org.opencontainers.image.title=MikTeX specific for ${{ matrix.name }} on Debian ${{ steps.variables.outputs.base_image_os_version }} (${{ steps.variables.outputs.base_image_os_codename }}) + Python ${{ steps.variables.outputs.base_image_py_version }}" \
-            --label "org.opencontainers.image.description=MikTeX specific for ${{ matrix.name }} on Debian ${{ steps.variables.outputs.base_image_os_version }} (${{ steps.variables.outputs.base_image_os_codename }}) + Python ${{ steps.variables.outputs.base_image_py_version }} image maintained by pyTooling Authors." \
+            --build-arg "IMAGE=${{ needs.MiKTeX.outputs.miktex_image }}" \
+            --label "org.opencontainers.image.title=MiKTeX specific for ${{ matrix.name }} on Debian ${{ steps.variables.outputs.base_image_os_version }} (${{ steps.variables.outputs.base_image_os_codename }}) + Python ${{ steps.variables.outputs.base_image_py_version }}" \
+            --label "org.opencontainers.image.description=MiKTeX specific for ${{ matrix.name }} on Debian ${{ steps.variables.outputs.base_image_os_version }} (${{ steps.variables.outputs.base_image_os_codename }}) + Python ${{ steps.variables.outputs.base_image_py_version }} image maintained by pyTooling Authors." \
             --label "org.opencontainers.image.authors=Patrick Lehmann <Paebbels@gmail.com>" \
             --label "org.opencontainers.image.vendor=pyTooling" \
             --label "org.opencontainers.image.version=1.0" \
@@ -220,7 +249,7 @@ jobs:
 
           printf -- "Docker image '%s' has %s\n" "${{ steps.variables.outputs.specific_image }}" "$(DockerImageSizeUncompressed ${{ steps.variables.outputs.specific_image }})"
 
-      - name: ☑ Checking MikTeX image '${{ steps.variables.outputs.specific_image }}'
+      - name: ☑ Checking MiKTeX image '${{ steps.variables.outputs.specific_image }}'
         run: |
           DockerImageSizeUncompressed() {
             docker image inspect $1 --format='{{.Size}}' | numfmt --to=iec --format '%.2f'
@@ -243,3 +272,18 @@ jobs:
         
           printf -- "Docker image '%s' has %s\n" "${{ steps.variables.outputs.specific_image }}" "$(DockerImageSizeUncompressed ${{ steps.variables.outputs.specific_image }})"
           docker image push ${{ steps.variables.outputs.specific_image }}
+
+  SanityCheck-Sphinx:
+    name: Check MiKTeX for Sphinx installation
+    runs-on: 'ubuntu-24.04'
+    needs:
+      - MiKTeX
+      - Specific
+    container:
+      image: ${{ needs.MiKTeX.outputs.miktex_image_ns }}/${{ needs.MiKTeX.outputs.miktex_image_name }}:sphinx
+      volumes:
+        - ${{ github.workspace }}/latex:/latex
+    steps:
+      - name: Check Mermaid
+        run: |
+          mmdc --version
